# Generated by Django 3.2.9 on 2021-11-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
    ]
