# Generated by Django 3.2.9 on 2021-11-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211117_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cv',
            field=models.ImageField(blank=True, upload_to='cvs'),
        ),
    ]
