# Generated by Django 3.2.9 on 2021-11-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_doctor_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.TextField(blank=True, max_length=10000.0),
        ),
    ]
