# Generated by Django 3.2.9 on 2021-11-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='degree_picture',
            field=models.ImageField(blank=True, upload_to='degrees'),
        ),
    ]
