# Generated by Django 3.2.9 on 2021-11-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_doctor_degree_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cv',
            field=models.TextField(blank=True, max_length=10000.0),
        ),
    ]
