# Generated by Django 4.0 on 2022-01-20 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_doctor_degree_remove_doctor_degree_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='degrees')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_doctor', to='users.doctor')),
            ],
        ),
    ]
